apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kustomize.component: tf-job-operator
  name: tfjobs.kubeflow.org
spec:
  additionalPrinterColumns:
    - JSONPath: .status.conditions[-1:].type
      name: State
      type: string
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
  group: kubeflow.org
  names:
    kind: TFJob
    plural: tfjobs
    singular: tfjob
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            tfReplicaSpecs:
              properties:
                Chief:
                  properties:
                    replicas:
                      maximum: 1
                      minimum: 1
                      type: integer
                PS:
                  properties:
                    replicas:
                      minimum: 1
                      type: integer
                Worker:
                  properties:
                    replicas:
                      minimum: 1
                      type: integer
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
    - name: v1beta2
      served: true
      storage: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: tf-job-dashboard
    kustomize.component: tf-job-operator
  name: tf-job-dashboard
  namespace: arena-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: tf-job-operator
    kustomize.component: tf-job-operator
  name: tf-job-operator
  namespace: arena-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: tf-job-dashboard
    kustomize.component: tf-job-operator
  name: tf-job-dashboard
rules:
  - apiGroups:
      - tensorflow.org
      - kubeflow.org
    resources:
      - tfjobs
      - tfjobs/status
    verbs:
      - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - '*'
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - pods/log
      - namespaces
    verbs:
      - '*'
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: tf-job-operator
    kustomize.component: tf-job-operator
  name: tf-job-operator
rules:
  - apiGroups:
      - tensorflow.org
      - kubeflow.org
    resources:
      - tfjobs
      - tfjobs/status
    verbs:
      - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - '*'
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
    verbs:
      - '*'
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: tf-job-dashboard
    kustomize.component: tf-job-operator
  name: tf-job-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tf-job-dashboard
subjects:
  - kind: ServiceAccount
    name: tf-job-dashboard
    namespace: arena-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: tf-job-operator
    kustomize.component: tf-job-operator
  name: tf-job-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tf-job-operator
subjects:
  - kind: ServiceAccount
    name: tf-job-operator
    namespace: arena-system
---
apiVersion: v1
data:
  controller_config_file.yaml: |-
    {
        "grpcServerFilePath": "/opt/mlkube/grpc_tensorflow_server/grpc_tensorflow_server.py"
    }
kind: ConfigMap
metadata:
  labels:
    kustomize.component: tf-job-operator
  name: tf-job-operator-config
  namespace: arena-system
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name: tfjobs-ui-mapping
      prefix: /tfjobs/
      rewrite: /tfjobs/
      service: tf-job-dashboard.kubeflow
  labels:
    kustomize.component: tf-job-operator
  name: tf-job-dashboard
  namespace: arena-system
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    kustomize.component: tf-job-operator
    name: tf-job-dashboard
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8443"
    prometheus.io/scrape: "true"
  labels:
    app: tf-job-operator
    kustomize.component: tf-job-operator
  name: tf-job-operator
  namespace: arena-system
spec:
  ports:
    - name: monitoring-port
      port: 8443
      targetPort: 8443
  selector:
    kustomize.component: tf-job-operator
    name: tf-job-operator
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    kustomize.component: tf-job-operator
  name: tf-job-dashboard
  namespace: arena-system
spec:
  selector:
    matchLabels:
      kustomize.component: tf-job-operator
  template:
    metadata:
      labels:
        kustomize.component: tf-job-operator
        name: tf-job-dashboard
    spec:
      containers:
        - command:
            - /opt/tensorflow_k8s/dashboard/backend
          env:
            - name: KUBEFLOW_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: registry.cn-zhangjiakou.aliyuncs.com/kubeflow-images-public/tf_operator:v0.6.0.rc0
          name: tf-job-dashboard
          ports:
            - containerPort: 8080
      serviceAccountName: tf-job-dashboard
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    kustomize.component: tf-job-operator
  name: tf-job-operator
  namespace: arena-system
spec:
  replicas: 1
  selector:
    matchLabels:
      kustomize.component: tf-job-operator
  template:
    metadata:
      labels:
        kustomize.component: tf-job-operator
        name: tf-job-operator
    spec:
      containers:
        - command:
            - /opt/kubeflow/tf-operator.v1
            - --alsologtostderr
            - -v=1
            - --monitoring-port=8443
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: registry.cn-zhangjiakou.aliyuncs.com/kubeflow-images-public/tf_operator:v0.6.0.rc0
          name: tf-job-operator
          volumeMounts:
            - mountPath: /etc/config
              name: config-volume
      serviceAccountName: tf-job-operator
      volumes:
        - configMap:
            name: tf-job-operator-config
          name: config-volume
