apiVersion: v1
kind: Namespace
metadata:
  name: arena-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sparkoperator
  namespace: arena-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sparkoperator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services", "configmaps", "secrets"]
  verbs: ["create", "get", "delete"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["create", "get", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "update", "patch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "get", "update", "delete"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create", "get", "update", "delete"]
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["sparkapplications", "scheduledsparkapplications"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sparkoperator
subjects:
  - kind: ServiceAccount
    name: sparkoperator
    namespace: arena-system
roleRef:
  kind: ClusterRole
  name: sparkoperator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkoperator
  namespace: arena-system
  labels:
    app.kubernetes.io/name: sparkoperator
    app.kubernetes.io/version: v2.4.0-v1beta1-0.8.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sparkoperator
      app.kubernetes.io/version: v2.4.0-v1beta1-0.8.1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sparkoperator
        app.kubernetes.io/version: v2.4.0-v1beta1-0.8.1
      initializers:
        pending: []
    spec:
      serviceAccountName: sparkoperator
      priorityClassName: system-cluster-critical
      containers:
      - name: sparkoperator
        image: registry.cn-zhangjiakou.aliyuncs.com/acs/spark-operator:v2.4.0-v1beta1-0.8.1
        imagePullPolicy: Always
        command: ["/usr/bin/spark-operator"]
        args:
        - -logtostderr
