---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: et-operator
    {{- include "arena.labels" . | nindent 4 }}
  name: et-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: et-operator
      {{- include "arena.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "arena.labels" . | nindent 8 }}
        app: et-operator
    spec:
      nodeSelector:
        {{- include "arena.nodeSelector" . | nindent 8 }}
        {{- include "arena.nonEdgeNodeSelector" . | nindent 8 }}
      tolerations:
      {{- include "arena.tolerateNonEdgeNodeSelector" . | nindent 6 }}
      containers:
        - args:
            - --enable-leader-election
            - --create-ssh-secret={{ .Values.createSSHSecret }}
          command:
            - /manager
          image: {{ include "arena.imagePrefix" . }}/{{ .Values.image }}:{{ .Values.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: manager
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: et-operator
      terminationGracePeriodSeconds: 10
