{{- if eq (include "crd.api" .) "v1beta1" -}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mpijobs.kubeflow.org
spec:
  group: kubeflow.org
  version: v1alpha1
  scope: Namespaced
  subresources:
    status: {}
  names:
    plural: mpijobs
    singular: mpijob
    kind: MPIJob
    shortNames:
    - mj
    - mpij
  validation:
    openAPIV3Schema:
      properties:
        spec:
          title: The MPIJob spec
          description: Either `gpus` or `replicas` should be specified, but not both
          oneOf:
          - properties:
              gpus:
                title: Total number of GPUs
                description: Valid values are 1, 2, 4, or any multiple of 8
                oneOf:
                - type: integer
                  enum:
                  - 1
                  - 2
                  - 4
                - type: integer
                  multipleOf: 8
                  minimum: 8
            required:
            - gpus
          - properties:
              replicas:
                title: Total number of replicas
                description: The GPU resource limit should be specified for each replica
                type: integer
                minimum: 1
            required:
            - replicas
{{- end }}
