{{- if eq .Values.sshSecret "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  config: {{ .Values.secretData.config }}
  id_rsa: {{ .Values.secretData.privateKey }}
  id_rsa.pub: {{ .Values.secretData.publicKey }}
{{- end }}

