{{- /*
Copyright 2025 The Kubeflow authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/ -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cron-operator.deployment.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cron-operator.labels" . | nindent 4 }}
  annotations:
    {{- include "cron-operator.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "cron-operator.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "cron-operator.labels" . | nindent 8 }}
      annotations:
        {{- include "cron-operator.annotations" . | nindent 8 }}
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: cron-operator
        image: {{ include "cron-operator.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy | default "IfNotPresent" }}
        command:
        - /manager
        args:
        - --workloads=Cron
        {{- if .Values.useHostTimezone }}
        volumeMounts:
        - name: volume-localtime
          mountPath: /etc/localtime
          readOnly: true
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        securityContext:
          seccompProfile:
            type: RuntimeDefault
      {{- if .Values.useHostTimezone }}
      volumes:
      - name: volume-localtime
        hostPath: 
          path: /etc/localtime
      {{- end }}
      nodeSelector:
        {{- include "cron-operator.nodeSelector" . | nindent 8 }}
      affinity:
        {{- include "cron-operator.affinity" . | nindent 8 }}
      tolerations:
      {{- include "cron-operator.tolerations" . | nindent 6 }}
      serviceAccountName: {{ include "cron-operator.serviceAccount.name" . }}
      terminationGracePeriodSeconds: 30
