apiVersion: v2

name: arena-artifacts

description: A Helm chart for installing arena dependencies.

type: application

kubeVersion: ">=1.16.0-0"

version: 0.15.2

appVersion: 0.15.2

home: https://github.com/kubeflow/arena

dependencies:
- name: tf-operator
  alias: tf
  version: 1.0.0
  repository: "@tf-operator"
  condition: tf.enabled,global.tf.enabled
- name: tf-dashboard
  alias: tfdashboard
  version: 0.1.0
  repository: "@tf-dashbard"
  condition: tfdashboard.enabled,global.tfdashboard.enabled
- name: cron-operator
  alias: cron
  version: 0.1.0
  repository: "@cron-operator"
  condition: cron.enabled,global.cron.enabled
- name: et-operator
  alias: et
  version: 0.1.1
  repository: "@et-operator"
  condition: et.enabled,global.et.enabled
- name: mpi-operator
  alias: mpi
  version: 0.1.0
  repository: "@mpi-operator"
  condition: mpi.enabled,global.mpi.enabled
- name: pytorch-operator
  alias: pytorch
  version: 0.1.0
  repository: "@pytorch-operator"
  condition: pytorch.enabled,global.pytorch.enabled
- name: gpu-exporter
  alias: exporter
  version: 0.1.0
  repository: "@gpu-exporter"
  condition: exporter.enabled,global.exporter.enabled
- name: elastic-job-supervisor
  alias: elastic-job-supervisor
  version: 0.1.0
  repository: "@elastic-job-supervisor"
  condition: elastic-job-supervisor.enabled,global.elastic-job-supervisor.enabled
