apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: {{ .Release.Name }}
spec:
  predictor:
    minReplicas: {{ .Values.minReplicas }}
    {{ .Values.modelType }}:
      storageUri: {{ .Values.storageUri }}