name: Question
description: Ask question about Arena
labels: ["kind/question", "lifecycle/needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this question!
  - type: textarea
    id: feature
    attributes:
      label: What question do you want to ask?
      description: |
        A clear and concise description of what you want to ask about Arena.
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Any additional context?
    validations:
      required: false
  - type: input
    id: votes
    attributes:
      label: Have the same question?
      value: Give it a 👍 We prioritize the question with most 👍
