apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: ack-prometheus-gpu-exporter
    {{- include "arena.labels" . | nindent 4 }}
  name: node-gpu-exporter
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http-metrics
    port: 9445
    protocol: TCP
    targetPort: 9445
  selector:
    k8s-app: ack-prometheus-gpu-exporter
  type: ClusterIP
