kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: arena:{{ .Release.Namespace }}:{{ .Release.Name }}
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - configmaps
    - services
    - deployments
    - nodes
    - nodes/*
    - services/proxy
    - persistentvolumes
    verbs:
    - get
    - list
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - list
    - get
  - apiGroups:
    - authentication.k8s.io
    resources:
    - tokenreviews
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get 
{{- with .Values.clusterRoles }}
{{- toYaml . | nindent 2 }}
{{- end }}
