{{- /*
Copyright 2025 The Kubeflow authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/ -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mpi-operator.deployment.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mpi-operator.labels" . | nindent 4 }}
  annotations:
    {{- include "mpi-operator.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "mpi-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mpi-operator.labels" . | nindent 8 }}
      annotations:
        {{- include "mpi-operator.annotations" . | nindent 8 }}
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: mpi-operator
        image: {{ include "mpi-operator.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy | default "IfNotPresent" }}
        args:
        - --gpus-per-node
        - "8"
        - --kubectl-delivery-image
        - {{ include "mpi-operator.kubectlDelivery.image" . }}
        - --alsologtostderr
        - --v=5
        {{- with .Values.resources }}
        resources:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        securityContext:
          seccompProfile:
            type: RuntimeDefault
      nodeSelector:
        {{- include "mpi-operator.nodeSelector" . | nindent 8 }}
      affinity:
        {{- include "mpi-operator.affinity" . | nindent 8 }}
      tolerations:
      {{- include "mpi-operator.tolerations" . | nindent 6 }}
      serviceAccountName: {{ include "mpi-operator.serviceAccount.name" . }}
      terminationGracePeriodSeconds: 30
