---
apiVersion: v1
kind: Secret
metadata:
  name: lws-webhook-server-cert
  namespace: {{ .Release.Namespace }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: lws-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: lws-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-leaderworkerset-x-k8s-io-v1-leaderworkerset
    failurePolicy: Fail
    name: mleaderworkerset.kb.io
    rules:
      - apiGroups:
          - leaderworkerset.x-k8s.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - leaderworkersets
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: lws-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate--v1-pod
    failurePolicy: Fail
    name: mpod.kb.io
    objectSelector:
      matchExpressions:
        - key: leaderworkerset.sigs.k8s.io/name
          operator: Exists
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: lws-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: lws-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-leaderworkerset-x-k8s-io-v1-leaderworkerset
    failurePolicy: Fail
    name: vleaderworkerset.kb.io
    rules:
      - apiGroups:
          - leaderworkerset.x-k8s.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - leaderworkersets
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: lws-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate--v1-pod
    failurePolicy: Fail
    name: vpod.kb.io
    objectSelector:
      matchExpressions:
        - key: leaderworkerset.sigs.k8s.io/name
          operator: Exists
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
    sideEffects: None