{{- if .Values.useTensorboard }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tensorboard
  labels:
    app: {{ template "pytorchjob.name" . }}
    chart: {{ template "pytorchjob.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: tensorboard
    createdBy: "PyTorchJob"
    controller-name: pytorch-operator
    group-name: kubeflow.org
    job-name: {{ .Release.Name }}
    pytorch-job-name: {{ .Release.Name }}
spec:
  type: {{ .Values.tensorboardServiceType }}
  ports:
    - port: 6006
      targetPort: 6006
      protocol: TCP
      name: tensorboard
  selector:
    app: {{ template "pytorchjob.name" . }}
    chart: {{ template "pytorchjob.chart" . }}
    release: {{ .Release.Name }}
    role: tensorboard
{{- end }}
