/*
Copyright 2021 The Alibaba Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/kubeflow/arena/pkg/operators/kubedl-operator/apis/apps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCrons implements CronInterface
type FakeCrons struct {
	Fake *FakeAppsV1alpha1
	ns   string
}

var cronsResource = schema.GroupVersionResource{Group: "apps", Version: "v1alpha1", Resource: "crons"}

var cronsKind = schema.GroupVersionKind{Group: "apps", Version: "v1alpha1", Kind: "Cron"}

// Get takes name of the cron, and returns the corresponding cron object, and an error if there is any.
func (c *FakeCrons) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Cron, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cronsResource, c.ns, name), &v1alpha1.Cron{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cron), err
}

// List takes label and field selectors, and returns the list of Crons that match those selectors.
func (c *FakeCrons) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CronList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cronsResource, cronsKind, c.ns, opts), &v1alpha1.CronList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CronList{ListMeta: obj.(*v1alpha1.CronList).ListMeta}
	for _, item := range obj.(*v1alpha1.CronList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested crons.
func (c *FakeCrons) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cronsResource, c.ns, opts))

}

// Create takes the representation of a cron and creates it.  Returns the server's representation of the cron, and an error, if there is any.
func (c *FakeCrons) Create(ctx context.Context, cron *v1alpha1.Cron, opts v1.CreateOptions) (result *v1alpha1.Cron, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cronsResource, c.ns, cron), &v1alpha1.Cron{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cron), err
}

// Update takes the representation of a cron and updates it. Returns the server's representation of the cron, and an error, if there is any.
func (c *FakeCrons) Update(ctx context.Context, cron *v1alpha1.Cron, opts v1.UpdateOptions) (result *v1alpha1.Cron, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cronsResource, c.ns, cron), &v1alpha1.Cron{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cron), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCrons) UpdateStatus(ctx context.Context, cron *v1alpha1.Cron, opts v1.UpdateOptions) (*v1alpha1.Cron, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cronsResource, "status", c.ns, cron), &v1alpha1.Cron{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cron), err
}

// Delete takes name of the cron and deletes it. Returns an error if one occurs.
func (c *FakeCrons) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cronsResource, c.ns, name), &v1alpha1.Cron{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCrons) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cronsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CronList{})
	return err
}

// Patch applies the patch and returns the patched cron.
func (c *FakeCrons) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Cron, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cronsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Cron{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Cron), err
}
