
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-supervisor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arena.labels" . | nindent 4 }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-supervisor
  labels:
    {{- include "arena.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - namespaces
  - serviceaccounts
  - secrets
  - persistentvolumeclaims
  - pods
  - pods/log
  - pods/exec
  - services
  - nodes
  verbs:
  - '*'
- apiGroups:
  - ""
  - apps
  - extensions
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - apps.kubedl.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - kubeflow.org
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - kai.alibabacloud.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - '*'
- apiGroups:
  - tensorflow.org
  resources:
  - '*'
  verbs:
  - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-supervisor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arena.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-supervisor
subjects:
- kind: ServiceAccount
  name: job-supervisor
  namespace: {{ .Release.Namespace }}