/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubeflow/arena/pkg/operators/edl-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTrainingJobSpecs implements TrainingJobSpecInterface
type FakeTrainingJobSpecs struct {
	Fake *FakeEdlV1alpha1
	ns   string
}

var trainingjobspecsResource = schema.GroupVersionResource{Group: "edl", Version: "v1alpha1", Resource: "trainingjobspecs"}

var trainingjobspecsKind = schema.GroupVersionKind{Group: "edl", Version: "v1alpha1", Kind: "TrainingJobSpec"}

// Get takes name of the trainingJobSpec, and returns the corresponding trainingJobSpec object, and an error if there is any.
func (c *FakeTrainingJobSpecs) Get(name string, options v1.GetOptions) (result *v1alpha1.TrainingJobSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(trainingjobspecsResource, c.ns, name), &v1alpha1.TrainingJobSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrainingJobSpec), err
}

// List takes label and field selectors, and returns the list of TrainingJobSpecs that match those selectors.
func (c *FakeTrainingJobSpecs) List(opts v1.ListOptions) (result *v1alpha1.TrainingJobSpecList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(trainingjobspecsResource, trainingjobspecsKind, c.ns, opts), &v1alpha1.TrainingJobSpecList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrainingJobSpecList), err
}

// Watch returns a watch.Interface that watches the requested trainingJobSpecs.
func (c *FakeTrainingJobSpecs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(trainingjobspecsResource, c.ns, opts))

}

// Create takes the representation of a trainingJobSpec and creates it.  Returns the server's representation of the trainingJobSpec, and an error, if there is any.
func (c *FakeTrainingJobSpecs) Create(trainingJobSpec *v1alpha1.TrainingJobSpec) (result *v1alpha1.TrainingJobSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(trainingjobspecsResource, c.ns, trainingJobSpec), &v1alpha1.TrainingJobSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrainingJobSpec), err
}

// Update takes the representation of a trainingJobSpec and updates it. Returns the server's representation of the trainingJobSpec, and an error, if there is any.
func (c *FakeTrainingJobSpecs) Update(trainingJobSpec *v1alpha1.TrainingJobSpec) (result *v1alpha1.TrainingJobSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(trainingjobspecsResource, c.ns, trainingJobSpec), &v1alpha1.TrainingJobSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrainingJobSpec), err
}

// Delete takes name of the trainingJobSpec and deletes it. Returns an error if one occurs.
func (c *FakeTrainingJobSpecs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(trainingjobspecsResource, c.ns, name), &v1alpha1.TrainingJobSpec{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTrainingJobSpecs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(trainingjobspecsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.TrainingJobSpecList{})
	return err
}

// Patch applies the patch and returns the patched trainingJobSpec.
func (c *FakeTrainingJobSpecs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TrainingJobSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(trainingjobspecsResource, c.ns, name, pt, data, subresources...), &v1alpha1.TrainingJobSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrainingJobSpec), err
}
