/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kubeflow/arena/pkg/operators/edl-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEnvSpecs implements EnvSpecInterface
type FakeEnvSpecs struct {
	Fake *FakeEdlV1alpha1
	ns   string
}

var envspecsResource = schema.GroupVersionResource{Group: "edl", Version: "v1alpha1", Resource: "envspecs"}

var envspecsKind = schema.GroupVersionKind{Group: "edl", Version: "v1alpha1", Kind: "EnvSpec"}

// Get takes name of the envSpec, and returns the corresponding envSpec object, and an error if there is any.
func (c *FakeEnvSpecs) Get(name string, options v1.GetOptions) (result *v1alpha1.EnvSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(envspecsResource, c.ns, name), &v1alpha1.EnvSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnvSpec), err
}

// List takes label and field selectors, and returns the list of EnvSpecs that match those selectors.
func (c *FakeEnvSpecs) List(opts v1.ListOptions) (result *v1alpha1.EnvSpecList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(envspecsResource, envspecsKind, c.ns, opts), &v1alpha1.EnvSpecList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnvSpecList), err
}

// Watch returns a watch.Interface that watches the requested envSpecs.
func (c *FakeEnvSpecs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(envspecsResource, c.ns, opts))

}

// Create takes the representation of a envSpec and creates it.  Returns the server's representation of the envSpec, and an error, if there is any.
func (c *FakeEnvSpecs) Create(envSpec *v1alpha1.EnvSpec) (result *v1alpha1.EnvSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(envspecsResource, c.ns, envSpec), &v1alpha1.EnvSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnvSpec), err
}

// Update takes the representation of a envSpec and updates it. Returns the server's representation of the envSpec, and an error, if there is any.
func (c *FakeEnvSpecs) Update(envSpec *v1alpha1.EnvSpec) (result *v1alpha1.EnvSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(envspecsResource, c.ns, envSpec), &v1alpha1.EnvSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnvSpec), err
}

// Delete takes name of the envSpec and deletes it. Returns an error if one occurs.
func (c *FakeEnvSpecs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(envspecsResource, c.ns, name), &v1alpha1.EnvSpec{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEnvSpecs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(envspecsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.EnvSpecList{})
	return err
}

// Patch applies the patch and returns the patched envSpec.
func (c *FakeEnvSpecs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.EnvSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(envspecsResource, c.ns, name, pt, data, subresources...), &v1alpha1.EnvSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.EnvSpec), err
}
