{{- if eq .Values.modelServiceExists false }}
apiVersion: v1
kind: Service
metadata:
  {{ if eq .Values.enableIstio true }}
  name:  {{ .Values.servingName }}
  {{ else }}
  name: {{ template "tensorflow-serving.fullname" . }}
  {{ end }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "tensorflow-serving.chart" . }}
    app: {{ template "tensorflow-serving.name" . }}
    servingName: {{ .Values.servingName }}
    servingVersion: "{{ .Values.servingVersion }}"
    servingType: "tf-serving"
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: grpc-serving
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
    - name: http-serving
      port: {{ .Values.restApiPort }}
      targetPort: {{ .Values.restApiPort }}
  selector:
    {{ if eq .Values.enableIstio true }}
    app: {{ template "tensorflow-serving.name" . }}
    serviceName: "{{ .Values.servingName }}"
    {{ else }}
    release: {{ .Release.Name | quote }}
    app: {{ template "tensorflow-serving.name" . }}
    {{ end }}
{{- end }}
