#{{- if eq .Values.modelServiceExists false }}
#apiVersion: v1
#kind: Service
#metadata:
#  name:  {{ .Values.servingName }}
#  labels:
#    heritage: {{ .Release.Service | quote }}
#    release: {{ .Release.Name | quote }}
#    chart: {{ template "custom-serving.chart" . }}
#    app: {{ template "custom-serving.name" . }}
#    servingName: {{ .Values.servingName }}
#    servingType: "custom-serving"
#spec:
#  type: {{ .Values.serviceType }}
#  ports:
#    - name: serving
#      port: {{ .Values.port }}
#      targetPort: {{ .Values.port }}
#    - name: http-serving
#      port: {{ .Values.restApiPort }}
#      targetPort: {{ .Values.restApiPort }}
#  selector:
#    app: {{ template "custom-serving.name" . }}
#    serviceName: "{{ .Values.servingName }}"
#    {{- if .Values.servingVersion }}
#    servingVersion: "{{ .Values.servingVersion }}"
#    {{- end }}
#{{- end }}
---
{{- if .Values.servingVersion }}
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.servingName }}-{{ .Values.servingVersion }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "custom-serving.chart" . }}
    app: {{ template "custom-serving.name" . }}
    servingName: {{ .Values.servingName }}
    servingVersion: "{{ .Values.servingVersion }}"
    servingType: "custom-serving"
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }} 
spec:
  type: {{ .Values.serviceType }}
  ports:
    {{- if ne (int .Values.port) 0 }}
    - name: grpc-serving
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
    {{- end }}
    {{- if ne (int .Values.restApiPort) 0 }}
    - name: restful-serving
      port: {{ .Values.restApiPort }}
      targetPort: {{ .Values.restApiPort }}
    {{- end }}
  selector:
    app: {{ template "custom-serving.name" . }}
    servingVersion: "{{ .Values.servingVersion }}"
{{- end }}
