{{- if .Values.servingVersion }}
apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.servingName }}-{{ .Values.servingVersion }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "custom-serving.chart" . }}
    app: {{ template "custom-serving.name" . }}
    servingName: {{ .Values.servingName }}
    servingVersion: "{{ .Values.servingVersion }}"
    servingType: "custom-serving"
  {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }} 
spec:
  type: {{ .Values.serviceType }}
  ports:
    {{- if ne (int .Values.port) 0 }}
    - name: grpc-serving
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
    {{- end }}
    {{- if ne (int .Values.restApiPort) 0 }}
    - name: restful-serving
      port: {{ .Values.restApiPort }}
      targetPort: {{ .Values.restApiPort }}
    {{- end }}
    {{- if ne (int .Values.metricsPort) 0 }}
    - name: metrics
      port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
    {{- end }}
  selector:
    app: {{ template "custom-serving.name" . }}
    servingVersion: "{{ .Values.servingVersion }}"
{{- end }}
