---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: pytorch-operator
    {{- include "arena.labels" . | nindent 4 }}
  name: pytorch-operator
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: pytorch-operator
    {{- include "arena.labels" . | nindent 4 }}
  name: pytorch-operator
rules:
  - apiGroups:
      - kubeflow.org
    resources:
      - pytorchjobs
      - pytorchjobs/status
    verbs:
      - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - events
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: pytorch-operator
    {{- include "arena.labels" . | nindent 4 }}
  name: pytorch-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pytorch-operator
subjects:
  - kind: ServiceAccount
    name: pytorch-operator
    namespace: {{ .Release.Namespace }}
