---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8443"
    prometheus.io/scrape: "true"
  labels:
    app: pytorch-operator
    {{- include "arena.labels" . | nindent 4 }}
  name: pytorch-operator
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: monitoring-port
      port: 8443
      targetPort: 8443
  selector:
    name: pytorch-operator
    {{- include "arena.labels" . | nindent 4 }}
  type: ClusterIP
