---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mpijobs.kubeflow.org
spec:
  group: kubeflow.org
  version: v1alpha1
  scope: Namespaced
  names:
    plural: mpijobs
    singular: mpijob
    kind: MPIJob
    shortNames:
    - mj
    - mpij
  validation:
    openAPIV3Schema:
      properties:
        spec:
          title: The MPIJob spec
          description: Either `gpus` or `replicas` should be specified, but not both
          oneOf:
          - properties:
              gpus:
                title: Total number of GPUs
                description: Valid values are 1, 2, 4, or any multiple of 8
                oneOf:
                - type: integer
                  enum:
                  - 1
                  - 2
                  - 4
                - type: integer
                  multipleOf: 8
                  minimum: 8
            required:
            - gpus
          - properties:
              replicas:
                title: Total number of replicas
                description: The GPU resource limit should be specified for each replica
                type: integer
                minimum: 1
            required:
            - replicas
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mpi-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  verbs:
  - create
  - list
  - watch
# This is needed for the launcher Role.
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
# This is needed for the launcher Role.
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs
  - mpijobs/status
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mpi-operator
  namespace: arena-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mpi-operator
  namespace: arena-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mpi-operator
subjects:
- kind: ServiceAccount
  name: mpi-operator
  namespace: arena-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpi-operator
  namespace: arena-system
  labels:
    app: mpi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpi-operator
  template:
    metadata:
      labels:
        app: mpi-operator
    spec:
      serviceAccountName: mpi-operator
      containers:
      - name: mpi-operator
        image: registry.cn-zhangjiakou.aliyuncs.com/kube-ai/mpi-operator:v20220125-05bf745
        args: [
          "--gpus-per-node", "8",
          "--kubectl-delivery-image",
          "registry.cn-zhangjiakou.aliyuncs.com/kube-ai/kubectl-delivery:latest",
          "--alsologtostderr",
          "-v=5"
        ]
        imagePullPolicy: Always
---

