apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    kustomize.component: tf-job-operator
    {{- include "arena.labels" . | nindent 4 }}
  name: tf-job-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      kustomize.component: tf-job-operator
      {{- include "arena.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        kustomize.component: tf-job-operator
        name: tf-job-operator
        {{- include "arena.labels" . | nindent 8 }}
    spec:
      nodeSelector:
        {{- include "arena.nodeSelector" . | nindent 8 }}
        {{- include "arena.nonEdgeNodeSelector" . | nindent 8 }}
      tolerations:
      {{- include "arena.tolerateNonEdgeNodeSelector" . | nindent 6 }}
      containers:
        - command:
            - /opt/kubeflow/tf-operator.v1
            - --alsologtostderr
            - -v=1
            - --monitoring-port=8443
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: {{ include "arena.imagePrefix" . }}/{{ .Values.image }}:{{ .Values.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: tf-job-operator
          volumeMounts:
            - mountPath: /etc/config
              name: config-volume
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      serviceAccountName: tf-job-operator
      volumes:
        - configMap:
            name: tf-job-operator-config
          name: config-volume
