apiVersion: v1
data:
  controller_config_file.yaml: |-
    {
        "grpcServerFilePath": "/opt/mlkube/grpc_tensorflow_server/grpc_tensorflow_server.py"
    }
kind: ConfigMap
metadata:
  labels:
    kustomize.component: tf-job-operator
    {{- include "arena.labels" . | nindent 4 }}
  name: tf-job-operator-config
  namespace: {{ .Release.Namespace }}
