apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8443"
    prometheus.io/scrape: "true"
  labels:
    app: tf-job-operator
    kustomize.component: tf-job-operator
    {{- include "arena.labels" . | nindent 4 }}
  name: tf-job-operator
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: monitoring-port
      port: 8443
      targetPort: 8443
  selector:
    kustomize.component: tf-job-operator
    name: tf-job-operator
    {{- include "arena.labels" . | nindent 4 }}
  type: ClusterIP
