apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-job-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: tf-job-operator
    kustomize.component: tf-job-operator
    {{- include "arena.labels" . | nindent 4 }}
