apiVersion: v1
kind: ConfigMap
metadata:
  name: rdma-devices
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arena.labels" . | nindent 4 }}
data:
  config.json: |
    {
        "mode" : "hca"
    }
