kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: arena-demo
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - get
- apiGroups:
  - ""
  - apps
  - extensions
  resources:
  - deployments
  - replicasets
  - statefulsets
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - tfjobs
  - mpijobs
  - pytorchjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kai.alibabacloud.com
  resources:
  - trainingjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - sparkapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.volcano.sh
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.sigs.k8s.io
  resources:
  - elasticquotas
  - elasticquotatrees
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - serving.kserve.io
  resources:
  - inferenceservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: arena-demo
  name: arena-demo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: arena-demo
  name: arena-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: arena-demo
subjects:
- kind: ServiceAccount
  name: arena-demo
  namespace: default
